### ISSUE TITLE
Fix crash bug with duplicate inputs within a transaction

### ISSUE THREAD

**Issue by jlautner** [floblockchain/flo#5]
https://github.com/floblockchain/flo/blob/e17497e0948f6360a76c31de1e794cb89e10ff72/src/validation.cpp#L2827

Just need to change this to true, update version, recompile, notify clients to update.

More details here:
https://github.com/bitcoin/bitcoin/commit/d926a87fde80b64024b2d94260c53aab20ccb259#diff-24efdb00bfbe56b140fb006b562cc70bL3125

**Comment by bitspill** [comment]
Was fixed with https://github.com/floblockchain/flo/commit/4d3b091eb269a6cc275aba669b86079639dd9676
