### ISSUE TITLE
Official Repo

### ISSUE THREAD

**Issue by oliverw** [floblockchain/flo#6]
I'm confused. Is this the official repo for Florincoin or it [this](https://github.com/florincoin/florincoin)? The second repo link to florincoin.org which redirects to flo.cash which in turn links to this repo.

**Comment by bitspill** [comment]
This is the official repository for FLO, we've been in the slow process of migrating from "florincoin" to just "Flo"

We should get a notice on that old repo though for sure, thanks for pointing it out.

**Comment by oliverw** [comment]
Understood. Should this brand change be reflected in that other project we are both contributing to? 😄

**Comment by bitspill** [comment]
Probably 😉

I should probably pop in a PR for that quick

Edit: done, https://github.com/coinfoundry/miningcore/pull/465
