### ISSUE TITLE
The partner instant exchange SimpleSwap.io

### ISSUE THREAD

**Issue by charlie-selle** [floblockchain/flo#7]
Hi,

I am Nicolas, the manager at SimpleSwap.io, an instant cryptocurrency exchange.

We present a simple and easy-to-use platform that works without registration and limits and allows users to make swaps in just two clicks.

We successfully support FLO on our service for a long time and we have been exchanging FLO for more than 200 coins to our customers. I tried to find contact with your team but without results.

I'm sorry that I invaded here, but maybe you can tell me where I can turn. I would like to make contact so we can have an interaction.

**Comment by metacoin** [comment]
@SimpleSwap  You can find team member contacts on the front page of our website flo.cash - we respond in Telegram, Slack, Twitter, and Discord within 2-3 hours on average, as our team is distributed worldwide. Please join one of those channels and reach out to a team member, or contact us here:
Twitter: https://twitter.com/floblockchain
Telegram: https://t.me/floblockchain

Or contact me directly here
Telegram: https://t.me/metacoin
